add `fd_manager` runtime module
hyperware-ai/hyperdrive pull request #561
Opened 2024-09-26 05:13 UTC by nick1udwig

## Problem

We run out of file descriptors because things like TCP sockets consume them: #556

## Solution

Introduce a new runtime module: `fd_manager`. It is pretty simple: it just tracks the number allowed `fd`s. Runtime modules that consume `fd`s must notify `fd_manager` when they open or close an `fd`. Then, if the total amount of `fd`s passes some threshold, `fd_manager` sends out a Request to all runtime modules with open `fd`s to `Cull` their old `fd`s with a suggested fraction to cull. Runtime modules that consume `fd`s must, therefore, also implement logic to respond to a `Cull`.

## Testing

TODO

## Docs Update

TODO

## Notes

TODO list:

- [x] Write `fd_manager` skeleton
- [ ] Write `fd_manager` helper `send_fd_manager_open(number_opened: u64)`
- [ ] Write `fd_manager` helper `send_fd_manager_close(number_opened: u64)`
- [ ] Update vfs to talk to `fd_manager`
- [ ] Update sqlite to talk to `fd_manager`
- [ ] Update kv to talk to `fd_manager`
- [ ] Update net to talk to `fd_manager`
- [ ] Look for any other consumers of fds and update them to talk to `fd_manager`
- [ ] Test

2024-09-30 18:46 UTC, dr-frmr commented on kinode/src/fd_manager.rs
> +            max_fds: DEFAULT_MAX_OPEN_FDS,
Shouldn't `update_max_fds` be called once here at the start, so default limit is not applied briefly at launch?

2024-10-01 19:24 UTC, nick1udwig commented
When booting a pre-existing indirect node with this binary I got a segfault. Not obvious to me where in the `net` code there is a hanging `peer`, but that's what this looks like to me:
```
Tue 09:51 net: connection lost with aficionad.os
Tue 09:51 net:distro:sys closed 1 of 20
diligence.os > m our@fd_manager:distro:sys "GetState"
Tue 09:52 process diligence.os@12665670855602396235:terminal:sys returned without error
Tue 09:52 process 12665670855602396235:terminal:sys has OnExit behavior None
Tue 09:52 kernel: killing process 12665670855602396235:terminal:sys
Tue 09:52 hq:uncentered.os: error: Internal sync failed: Failed to generate embeddings: Timeout
Tue 09:53 net: attempting to connect to aficionad.os directly
Tue 09:53 net: connected to aficionad.os directly
diligence.os > thread 'tokio-runtime-worker' panicked at kinode/src/net/connect.rs:11:30:
                                                                                         net: peer sender was dropped: SendError { .. }
                                    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
              Cleaning up "/home/nick/kinode-homes/diligence.os"...
Done cleaning up "/home/nick/kinode-homes/diligence.os".
```
Will look more into this this afternoon

2024-10-02 00:13 UTC, nick1udwig commented
Pretty sure I got it; confirming then fix coming here.

2024-10-02 03:20 UTC, nick1udwig commented
Fixed in aca7985. Unrelated fixes in a2fa276

2024-10-07 03:37 UTC, dr-frmr commented
By my count, the kernel / runtime itself uses about 20 file descriptors in the base case. I suggest that instead of configuring kernel, sqlite, kv, and terminal to use fd_manager, we simply add a fixed buffer that reserves the runtime FDs. Only vfs and net dynamically use a bunch of FDs / have the potential to overwhelm a limit at the moment.

Currently fd_manger uses a constant to give cushion from what the system gives:
```
const DEFAULT_FDS_AS_FRACTION_OF_ULIMIT_PERCENTAGE: u64 = 60;
```

I suggest that this gets bumped up to 90 and we tack on `30` as a fixed value that gets subtracted from whatever system ulimit we are given. If we are given less than 40 from system (which would give `9` as the final amount available to vfs/net.. not much to work with..) we crash with a descriptive error.

2024-10-07 16:26 UTC, bitful-pannul commented
> I suggest that instead of configuring kernel, sqlite, kv, and terminal to use fd_manager, we simply add a fixed buffer that reserves the runtime FDs. Only vfs and net dynamically use a bunch of FDs / have the potential to overwhelm a limit at the moment.

This doesn't necessarily have to be in 0.9.5 yet, but kv and sqlite FDs can definitely use a bunch of FDs (loop open 500 sqlite dbs will error), if users have many apps installed that use them, should be quite simple to cull them given most open actions are already OpenOrCreate.

2024-10-07 17:14 UTC, nick1udwig commented
I'm ok with hardcoding stuff for now to get a functional version out for our users, but definitely would want to have a less-hardcoded solution in the future.

2024-10-07 19:13 UTC, dr-frmr commented
> kv and sqlite FDs can definitely use a bunch of FDs

Wait really? I thought that both of these used one "db" and parceled userspace requests into separate tables and such.. if a new file descriptor is acquired we should def track

2024-10-07 19:20 UTC, dr-frmr commented
I see now that multiple DBs get opened. I'll wire these up to fd_manager.

2024-10-08 00:17 UTC, dr-frmr commented
@bitful-pannul need to you check my work here on refactor to `kv`. `sqlite` coming next

2024-10-08 02:02 UTC, dr-frmr commented
Sqlite work added.

2024-10-08 18:13 UTC, barraguda requested changes

2024-10-08 18:13 UTC, bitful-pannul commented on kinode/src/sqlite.rs
> +        let _ = fs::remove_dir_all(&db_path).await;
this removes the actual db, should just close the in-memory connection

2024-10-08 18:13 UTC, bitful-pannul commented on kinode/src/kv.rs
> +        let _ = fs::remove_dir_all(&db_path).await;
+1, removes the db instead of closing the connection

2024-10-08 18:19 UTC, bitful-pannul commented on kinode/src/sqlite.rs
> +    }
should also update access order even if open_dbs.contains_key() returns true?

2024-10-08 22:04 UTC, nick1udwig commented on kinode/src/sqlite.rs
> +            ));
We should never swallow `Result`s like this. It makes debugging really hard if an error ever starts being emitted. Either `unwrap()` it or -- at a minimum -- log it

2024-10-08 23:53 UTC, merged